### ISSUE TITLE
category/package-version highlighting

### ISSUE THREAD

**Issue by TheChymera** [gentoo/gentoo-syntax#13]
In `nano` I get very nice highlighting corresponding to the Package Manager Specification "CPV" naming scheme:

![screenshot from 2017-08-02 03-31-46](https://user-images.githubusercontent.com/950524/28853823-6ab9ffc0-7733-11e7-8479-ec1eafe28651.png)

In `vim` (having installed this package) I get the following, considerably lamer, highlighting: 

![screenshot from 2017-08-02 03-31-55](https://user-images.githubusercontent.com/950524/28853830-785d8eb2-7733-11e7-9a39-4486dd53ebfa.png)

Is this the intended effect, or have I failed to enable something about this plug-in. If this actually is the intended highlighting, what would be needed to improve it?

`eix` tells me I have:

```
[I] app-editors/vim
     Available versions:  8.0.0386 (~)8.0.0386-r1 **9999 {X acl cscope debug gpm lua luajit minimal nls perl python racket ruby selinux tcl vim-pager PYTHON_SINGLE_TARGET="python2_7 python3_4 python3_5 python3_6" PYTHON_TARGETS="python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  8.0.0386-r1(09:27:56 06.06.2017)(X acl gpm nls -cscope -debug -lua -luajit -minimal -perl -python -racket -ruby -selinux -tcl -vim-pager PYTHON_SINGLE_TARGET="python3_4 -python2_7 -python3_5 -python3_6" PYTHON_TARGETS="python2_7 python3_4 -python3_5 -python3_6")
     Homepage:            http://www.vim.org/ https://github.com/vim/vim
     Description:         Vim, an improved vi-style text editor
```

and 

```
[I] app-vim/gentoo-syntax
     Available versions:  20160530 20170225 **99999999 {ignore-glep31}
     Installed versions:  20170225(01:14:34 11.04.2017)(-ignore-glep31)
     Homepage:            https://github.com/gentoo/gentoo-syntax
     Description:         Gentoo and portage related syntax highlighting, filetype, and indent settings
```

**Comment by radhermit** [comment]
This is something that will require additional support to be added to the related pkg atom matching sections for the various file types. I'd welcome pullreqs/patches if you feel like delving into vimscript. :smile:

**Comment by TheChymera** [comment]
@radhermit I know next to nothing about vimscript, I might give it a try, though. Could you link me to the relevant code bits?

**Comment by mgorny** [comment]
I'll try to implement it when I have some time today. However, it's going to be a bit hard given the insanity of Gentoo PN-PV syntax.

**Comment by mgorny** [comment]
I've experimented with a bit and my conclusion is 'nope'. Firstly, because parsing all the intricacies of package dependency syntax is insane. Secondly, because all this ends up being too colorful to have any practical value.

**Comment by TheChymera** [comment]
Would you say the [nano palette](https://user-images.githubusercontent.com/950524/28853823-6ab9ffc0-7733-11e7-8479-ec1eafe28651.png) is too colorful to have any value?
