### ISSUE TITLE
Add Shellcheck support

### ISSUE THREAD

**Issue by XVilka** [gentoo/gentoo-syntax#26]
To analyze the ebuild/eclass files without the warnings of undefined EAPI variables and functions.
See https://github.com/koalaman/shellcheck/issues/1341

**Comment by radhermit** [comment]
This kind of functionality would make more sense to integrate into a ebuild/eclass linter, e.g. pkgcheck or repoman, which then your chosen editor could hook into.

However, I'm slightly biased since that's what I'm already working on but it doesn't use shellcheck. :smile:

**Comment by msva** [comment]
Yeah, shellcheck is a linter, which supposed to be used separately (as {n,}vim plugin, or as LSP-server plugin), and not in syntax-files.
