### ISSUE TITLE
strip-linguas

### ISSUE THREAD

**Issue by jonasstein** [gentoo/gentoo-syntax#37]
please add syntax highlighting for `strip-linguas` in the list of valid `inherit`s

**Comment by msva** [comment]
Actually, it shouldn't be "on list of invalid ones".

I mean, there is no lists neither for "valid" nor for "invalid" entries for `inherit`.
So, it shouldn't be highlighted as an error (or what did you mean?).
But (!!!) it has it's highlights a keyword (even on list of inherit, lol)

![image](https://github.com/user-attachments/assets/9aeaada3-9883-4524-a9b4-6febbd4b691c)
