### ISSUE TITLE
Remapping of leader key in bugsummary.vim

### ISSUE THREAD

**Issue by iankeane** [gentoo/gentoo-syntax#4]
There is a mapping in bugsummary.vim (line 155) to <leader>bug that should probably be mapped to something else; especially since this is part of a plugin included in vim by default when downloaded from portage, and leader shortcuts are meant to be set for personal use.

Specifically, this affects me because I have a personal mapping to <leader>b, and when I use that mapping it pauses in order to determine if I am going to type <leader>b or <leader>bug. 

Thanks for your time and attention, have a nice week.

**Comment by radhermit** [comment]
I'm considering just tossing the entire file since I've never used it, pybugz and similar are much more usable from the terminal, and it isn't really syntax related.

I assume you only care about it because it conflicts with your keybindings and therefore wouldn't mind if it disappeared? :wink:

**Comment by iankeane** [comment]
Apart from the behavior I mentioned, I'm not really aware of what this file does, so I'd say it's up to your discretion.

Thanks for the quick response!
